[master conf]
master = true
expect-workers = 2

[runtime settings]
host = https://petstore.octoperf.com
web-port = 8089
# users = 3
# spawn-rate = 1
# locustfile = petstore.py
locustfile = distributedLoadTesting\petstore.py
# run-time = 60s
headless = false
# only-summary = true
# html = distributedLoadTesting/petstore_report_ui_mode.html
